# -*- coding: utf-8 -*-
"""CROP_DISESE_DETION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wp10E16bZhBDOv-L_5-Luq6pRiaiHDsy
"""

!pip install -q kagglehub

import kagglehub

path = kagglehub.dataset_download(
    "vipoooool/new-plant-diseases-dataset"
)

print("Downloaded to:")
print(path)

import os

DATA_DIR = path

TRAIN_DIR = os.path.join(
    DATA_DIR,
    "New Plant Diseases Dataset(Augmented)",
    "New Plant Diseases Dataset(Augmented)",
    "train"
)

VALID_DIR = os.path.join(
    DATA_DIR,
    "New Plant Diseases Dataset(Augmented)",
    "New Plant Diseases Dataset(Augmented)",
    "valid"
)

print("TRAIN_DIR:", TRAIN_DIR)
print("VALID_DIR:", VALID_DIR)

import os

print("Train exists:", os.path.exists(TRAIN_DIR))
print("Validation exists:", os.path.exists(VALID_DIR))

from tensorflow import keras

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = keras.utils.image_dataset_from_directory(
    TRAIN_DIR,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=42
)

val_ds = keras.utils.image_dataset_from_directory(
    VALID_DIR,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

import os
import cv2
import matplotlib.pyplot as plt

# Get the class folders
classes = os.listdir(TRAIN_DIR)

# Pick the first class
class_name = classes[0]

# Path to that class folder
class_dir = os.path.join(TRAIN_DIR, class_name)

# Get the first image
image_name = os.listdir(class_dir)[0]

# Complete image path
image_path = os.path.join(class_dir, image_name)

# Read image
img = cv2.imread(image_path)

# OpenCV loads images as BGR, so convert to RGB
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Display
plt.imshow(img)
plt.title(class_name)
plt.axis("off")
plt.show()

num_classes = len(class_names)

print("Number of classes:", num_classes)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


class_names = train_ds.class_names

num_classes = len(class_names)

print(num_classes)


base_model = keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False

model = keras.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

loss, accuracy = model.evaluate(val_ds)

print("Validation Accuracy:", accuracy * 100, "%")