# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClddwYUuDXFcOSMkWWhbnr3qGjYHTrEY
"""

!pip install face-recognition

import face_recognition

print("face_recognition installed successfully!")

import numpy as np
import torch
import torch.nn as nn
import cv2
import face_recognition
from torchvision import transforms
import torch.nn.functional as F

pip install torch torchvision transformers opencv-python face-recognition pillow

!pip install torch torchvision transformers opencv-python face-recognition pillow

import cv2
import torch
import torch.nn.functional as F
import face_recognition

from PIL import Image
from transformers import AutoImageProcessor, AutoModelForImageClassification



MODEL_NAME = "trpakov/vit-face-expression"



class EmotionRecognizer:

    def __init__(self):

        self.device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

        print("Device:", self.device)


        print("Loading image processor...")

        self.processor = AutoImageProcessor.from_pretrained(
            MODEL_NAME
        )


        print("Loading emotion model...")

        self.model = AutoModelForImageClassification.from_pretrained(
            MODEL_NAME
        )

        self.model = self.model.to(self.device)


        self.model.eval()

        print("Model loaded successfully!")


        self.emotions = self.model.config.id2label

        print("\nEmotion classes:")

        for index, emotion in self.emotions.items():
            print(f"{index} = {emotion}")



    def process_frame(self, frame):


        rgb_frame = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        face_locations = face_recognition.face_locations(
            rgb_frame
        )

        results = []

        for face_location in face_locations:

            top, right, bottom, left = face_location


            face_image = rgb_frame[
                top:bottom,
                left:right
            ]


            if face_image.size == 0:
                continue


            face_pil = Image.fromarray(face_image)


            inputs = self.processor(
                images=face_pil,
                return_tensors="pt"
            )


            inputs = {
                key: value.to(self.device)
                for key, value in inputs.items()
            }


            with torch.no_grad():

                outputs = self.model(**inputs)

                # Convert logits to probabilities
                probabilities = F.softmax(
                    outputs.logits,
                    dim=1
                )

                # Find highest probability
                emotion_index = torch.argmax(
                    probabilities,
                    dim=1
                ).item()

                confidence = probabilities[
                    0,
                    emotion_index
                ].item()


            emotion = self.emotions[emotion_index]


            results.append({
                "emotion": emotion,
                "confidence": confidence,
                "location": face_location
            })

        return results




def main():


    recognizer = EmotionRecognizer()


    cap = cv2.VideoCapture(0)


    if not cap.isOpened():

        print("\nERROR: Could not open webcam.")
        print("Check whether your camera is connected.")
        return

    print("\nWebcam started.")
    print("Press Q to quit.")


    while True:

        ret, frame = cap.read()


        if not ret:

            print("ERROR: Could not read webcam frame.")
            break

        results = recognizer.process_frame(frame)


        for result in results:

            top, right, bottom, left = result["location"]

            emotion = result["emotion"]
            confidence = result["confidence"]


            cv2.rectangle(
                frame,
                (left, top),
                (right, bottom),
                (0, 255, 0),
                2
            )


            confidence_percent = confidence * 100

            text = (
                f"{emotion}: "
                f"{confidence_percent:.1f}%"
            )


            cv2.putText(
                frame,
                text,
                (left, max(top - 10, 25)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (0, 255, 0),
                2
            )


        cv2.imshow(
            "Real-Time Emotion Recognition",
            frame
        )


        key = cv2.waitKey(1) & 0xFF

        if key == ord("q"):

            break


    cap.release()


    cv2.destroyAllWindows()

    print("Program stopped.")



main()